x-fern-pagination: 
  offset: $request.page
  results: $response.records

paths:
  /prompts:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List prompts
          response:
            body:
              records:
                - id: "pr_123abc"
                  path: "customer-service"
                  name: "customer-service"
                  version_id: "pv_456def"
                  type: "prompt"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  status: "committed"
                  last_used_at: "2024-05-01T12:00:00Z"
                  model: "gpt-4"
                  version_logs_count: 1
                  total_logs_count: 1
                  inputs:
                    - name: "customer_query"
  /tools:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List tools
          response:
            body:
              records:
                - id: "tl_789ghi"
                  path: "math-tool"
                  name: "math-tool"
                  version_id: "tv_012jkl"
                  type: "tool"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  status: "committed"
                  last_used_at: "2024-05-01T12:00:00Z"
                  version_logs_count: 1
                  total_logs_count: 1
                  inputs:
                    - name: "operation"
  /datasets:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List datasets
          response:
            body:
              records:
                - id: "ds_345mno"
                  path: "test-questions"
                  name: "test-questions"
                  version_id: "dsv_678pqr"
                  type: "dataset"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  status: "committed"
                  last_used_at: "2024-05-01T12:00:00Z"
                  datapoints_count: 2
  /datasets/{id}/datapoints:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List datapoints
          path-parameters:
            id: "ds_345mno"
          response:
            body:
              records:
                - id: "dp_901stu"
                  inputs:
                    question: "What is the capital of France?"
                  target:
                    answer: "Paris"
                - id: "dp_234vwx"
                  inputs:
                    question: "Who wrote Hamlet?"
                  target:
                    answer: "William Shakespeare"
              page: 1
              size: 10
              total: 2
  /evaluations:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List evaluations
          query-parameters:
            file_id: "file_123abc"
          response:
            body:
              records:
                - id: "ev_567yza"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  status: "completed"
                  dataset:
                    id: "ds_345mno"
                    name: "Test Dataset"
                    path: "test-dataset"
                    version_id: "dsv_678pqr"
                    created_at: "2024-05-01T12:00:00Z"
                    updated_at: "2024-05-01T12:00:00Z"
                    status: "committed"
                    last_used_at: "2024-05-01T12:00:00Z"
                    datapoints_count: 100
                  evaluatees:
                    - version: {}
                      orchestrated: false
                  evaluators:
                    - version: {}
                      orchestrated: false
              page: 1
              size: 10
              total: 1
  /evaluators:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List evaluators
          response:
            body:
              records:
                - id: "evr_890bcd"
                  name: "Accuracy Evaluator"
                  path: "accuracy-evaluator"
                  version_id: "ev_012def"
                  type: "evaluator"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  status: "committed"
                  last_used_at: "2024-05-01T12:00:00Z"
                  spec:
                    arguments_type: "target_required"
                    return_type: "number"
                    prompt:
                      content: "Evaluate the accuracy of the answer."
                  version_logs_count: 1
                  total_logs_count: 1
                  inputs:
                    - name: "answer"
  /logs:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List logs
          query-parameters:
            file_id: "file_123abc"
          response:
            body:
              records:
                - id: "log_123efg"
                  created_at: "2024-05-01T12:00:00Z"
                  output: "This is a sample output."
                  prompt:
                    id: "pr_123abc"
                    name: "Test Prompt"
                    path: "test-prompt"
                    version_id: "pv_456def"
                    created_at: "2024-05-01T12:00:00Z"
                    updated_at: "2024-05-01T12:00:00Z"
                    status: "committed"
                    last_used_at: "2024-05-01T12:00:00Z"
                    model: "gpt-4"
                    version_logs_count: 1
                    total_logs_count: 1
                    inputs:
                      - name: "question"
              page: 1
              size: 10
              total: 1
  /sessions:
    get:
      x-fern-pagination: true
      x-fern-examples:
        - name: List sessions
          response:
            body:
              records:
                - id: "sess_456hij"
                  created_at: "2024-05-01T12:00:00Z"
                  updated_at: "2024-05-01T12:00:00Z"
                  logs: []
              page: 1
              size: 10
              total: 1

  /prompts/call:
    post:
      x-fern-examples:
        - name: Simple
          request:
            path: "persona"
            prompt:
              model: "gpt-4"
              template:
                - role: "system"
                  content: "You are {{person}}. Answer any questions as this person. Do not break character."
            messages:
              - role: "user"
                content: "What really happened at Roswell?"
            inputs: 
              person: "Trump"
            stream: false
          response:
            body:
              prompt:
                id: "pr_3usCu3dAkgrXTlufrvPs7"
                path: "persona"
                name: "persona"
                version_id: "pv_Wu6zx1lAWJRqOyL8nWuZk"
                type: "prompt"
                created_at: "2024-05-01T12:00:00Z"
                updated_at: "2024-05-01T12:00:00Z"
                status: "committed"
                last_used_at: "2024-05-01T12:00:00Z"
                model: "gpt-4"
                template:
                  - role: "system"
                    content: "You are {{person}}. Answer any questions as this person. Do not break character."
                provider: "openai"
                version_logs_count: 1
                total_logs_count: 1
                inputs:
                  - name: "person"
              id: "data_fIfEb1SoKZooqeFbi9IFs"
              logs:
                - output: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                  raw_output: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                  created_at: "2024-05-01T12:00:00Z"
                  finish_reason: "stop"
                  output_message:
                    content: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                    role: "assistant"
                  prompt_tokens: 34
                  output_tokens: 125
                  index: 0

  /tools/log:
    post:
      x-fern-examples:
        - name: Tool log
          request:
            path: "math-tool"
            tool:
              function:
                name: "multiply"
                description: "Multiply two numbers"
                parameters:
                  type: "object"
                  properties:
                    a: 
                      type: "number"
                    b:
                      type: "number"
                  required: ["a", "b"]
            inputs:
              a: 5
              b: 7  
            output: "35"
          response:
            body:
              id: "data_abc123"
              tool_id: "tl_def456"
              version_id: "tv_ghi789"
              session_id: "sess_jkl012"

  /datasets:
    post:
      x-fern-examples:
        - name: Create dataset
          request:
            path: "test-questions"
            datapoints:
              - inputs:
                  question: "What is the capital of France?"
                target:
                  answer: "Paris"  
              - inputs:  
                  question: "Who wrote Hamlet?"
                target:
                  answer: "William Shakespeare"
            commit_message: "Initial dataset creation"
          response:
            body:
              id: "ds_mno345"
              path: "test-questions"
              name: "test-questions" 
              version_id: "dsv_pqr678"
              type: "dataset"
              created_at: "2024-05-01T12:00:00Z"
              updated_at: "2024-05-01T12:00:00Z"
              status: "committed"
              last_used_at: "2024-05-01T12:00:00Z"
              datapoints_count: 2

components:
  schemas:
    Body_Evaluations_updateStatus:
      x-fern-type-name: UpdateEvaluationStatusRequest
    PaginatedData_DatapointResponse_:
      x-fern-type-name: PaginatedDatapointResponse
    PaginatedData_DatasetResponse_:
      x-fern-type-name: PaginatedDatasetResponse
    PaginatedData_EvaluationResponse_:
      x-fern-type-name: PaginatedEvaluationResponse
    PaginatedData_PromptLogResponse_:
      x-fern-type-name: PaginatedPromptLogResponse
    PaginatedData_SessionResponse_:
      x-fern-type-name: PaginatedSessionResponse
    src__domain__chat_types__enums__ToolType:
      x-fern-type-name: ChatToolType
    src__domain__files__tool__ToolType:
      x-fern-type-name: FilesToolType
    src__external__app__models__v4__configs__ToolResponse:
      x-fern-type-name: ConfigToolResponse
    src__external__app__models__v4__feedback__FeedbackType:
      x-fern-type-name: FeedbackType
    src__external__app__models__v4__orgs__base_models__UserResponse:
      x-fern-type-name: BaseModelsUserResponse
    src__external__app__models__v5__datasets__DatasetRequest:
      x-fern-type-name: DatasetsRequest
    src__external__app__models__v5__evaluations__DatasetRequest:
      x-fern-type-name: EvaluationsDatasetRequest
    src__external__app__models__v5__evaluations__EvaluatorRequest:
      x-fern-type-name: EvaluationsRequest
    src__external__app__models__v5__evaluators__EvaluatorRequest:
      x-fern-type-name: EvaluatorsRequest
    src__external__app__models__v5__feedback__FeedbackType:
      x-fern-type-name: FeedbackType
    src__external__app__models__v5__tools__ToolResponse:
      x-fern-type-name: ToolResponse
    src__external__app__models__v5__users__UserResponse:
      x-fern-type-name: UserResponse
  securitySchemes: 
    APIKeyHeader: 
      x-fern-header: 
        env: HUMANLOOP_API_KEY
