x-fern-pagination: 
  offset: $request.page
  results: $response.records

paths:
  /prompts:
    get:
      x-fern-pagination: true
  /tools:
    get:
      x-fern-pagination: true
  /datasets:
    get:
      x-fern-pagination: true
  /datasets/{id}/datapoints:
    get:
      x-fern-pagination: true
  /evaluations:
    get:
      x-fern-pagination: true
  /evaluators:
    get:
      x-fern-pagination: true
  /logs:
    get:
      x-fern-pagination: true
  /sessions:
    get:
      x-fern-pagination: true

paths:
  /prompts/call:
    post:
      x-fern-examples:
        - name: Simple
          request:
            path: "persona"
            prompt:
              model: "gpt-4"
              template:
                - role: "system"
                  content: "You are {{person}}. Answer any questions as this person. Do not break character."
            messages:
              - role: "user"
                content: "What really happened at Roswell?"
            inputs: 
              person: "Trump"
            stream: false
          response:
            body:
              prompt:
                id: "pr_3usCu3dAkgrXTlufrvPs7"
                path: "persona"
                name: "persona"
                version_id: "pv_Wu6zx1lAWJRqOyL8nWuZk"
                type: "prompt"
                created_at: "2023-05-01T12:00:00Z"
                updated_at: "2023-05-01T12:00:00Z"
                status: "committed"
                last_used_at: "2023-05-01T12:00:00Z"
                model: "gpt-4"
                template:
                  - role: "system"
                    content: "You are {{person}}. Answer any questions as this person. Do not break character."
                provider: "openai"
                version_logs_count: 1
                total_logs_count: 1
                inputs:
                  - name: "person"
              id: "data_fIfEb1SoKZooqeFbi9IFs"
              logs:
                - output: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                  raw_output: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                  created_at: "2023-05-01T12:00:00Z"
                  finish_reason: "stop"
                  output_message:
                    content: "Well, let me tell you, there are a lot of stories about Roswell, and I hear them all the time. People love to talk about Roswell. So many theories, so many ideas. Some folks believe it was a weather balloon, others say it was something out of this world. Believe me, there's plenty that we don't know. Very interesting to look into, but the truth, well, it might still be out there. Could be a great story, who knows? But what I do know, folks, is that we have to keep our eyes open and always be on the lookout for the truth!"
                    role: "assistant"
                  prompt_tokens: 34
                  output_tokens: 125
                  index: 0

  /tools/log:
    post:
      x-fern-examples:
        - name: Tool log
          request:
            path: "math-tool"
            tool:
              function:
                name: "multiply"
                description: "Multiply two numbers"
                parameters:
                  type: "object"
                  properties:
                    a: 
                      type: "number"
                    b:
                      type: "number"
                  required: ["a", "b"]
            inputs:
              a: 5
              b: 7  
            output: "35"
          response:
            body:
              id: "data_abc123"
              tool_id: "tl_def456"
              version_id: "tv_ghi789"
              session_id: "sess_jkl012"

  /datasets:
    post:
      x-fern-examples:
        - name: Create dataset
          request:
            path: "test-questions"
            datapoints:
              - inputs:
                  question: "What is the capital of France?"
                target:
                  answer: "Paris"  
              - inputs:  
                  question: "Who wrote Hamlet?"
                target:
                  answer: "William Shakespeare"
            commit_message: "Initial dataset creation"
          response:
            body:
              id: "ds_mno345"
              path: "test-questions"
              name: "test-questions" 
              version_id: "dsv_pqr678"
              type: "dataset"
              created_at: "2023-05-01T12:00:00Z"
              updated_at: "2023-05-01T12:00:00Z"
              status: "committed"
              last_used_at: "2023-05-01T12:00:00Z"
              datapoints_count: 2

components:
  schemas:
    Body_Evaluations_updateStatus:
      x-fern-type-name: UpdateEvaluationStatusRequest
    PaginatedData_DatapointResponse_:
      x-fern-type-name: PaginatedDatapointResponse
    PaginatedData_DatasetResponse_:
      x-fern-type-name: PaginatedDatasetResponse
    PaginatedData_EvaluationResponse_:
      x-fern-type-name: PaginatedEvaluationResponse
    PaginatedData_PromptLogResponse_:
      x-fern-type-name: PaginatedPromptLogResponse
    PaginatedData_SessionResponse_:
      x-fern-type-name: PaginatedSessionResponse
    src__domain__chat_types__enums__ToolType:
      x-fern-type-name: ChatToolType
    src__domain__files__tool__ToolType:
      x-fern-type-name: FilesToolType
    src__external__app__models__v4__configs__ToolResponse:
      x-fern-type-name: ConfigToolResponse
    src__external__app__models__v4__feedback__FeedbackType:
      x-fern-type-name: FeedbackType
    src__external__app__models__v4__orgs__base_models__UserResponse:
      x-fern-type-name: BaseModelsUserResponse
    src__external__app__models__v5__datasets__DatasetRequest:
      x-fern-type-name: DatasetsRequest
    src__external__app__models__v5__evaluations__DatasetRequest:
      x-fern-type-name: EvaluationsDatasetRequest
    src__external__app__models__v5__evaluations__EvaluatorRequest:
      x-fern-type-name: EvaluationsRequest
    src__external__app__models__v5__evaluators__EvaluatorRequest:
      x-fern-type-name: EvaluatorsRequest
    src__external__app__models__v5__feedback__FeedbackType:
      x-fern-type-name: FeedbackType
    src__external__app__models__v5__tools__ToolResponse:
      x-fern-type-name: ToolResponse
    src__external__app__models__v5__users__UserResponse:
      x-fern-type-name: UserResponse
  securitySchemes: 
    APIKeyHeader: 
      x-fern-header: 
        env: HUMANLOOP_API_KEY
