import yaml
import json
import os
from jinja2 import Environment, BaseLoader


ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(ROOT_DIR, 'fern/apis/v5/openapi/')
EXAMPLES_DIR = os.path.join(TEMPLATE_DIR, 'examples')
TEMPLATE_FILE = 'template.yml'

def load_json(file_name):
    with open(file_name, 'r') as f:
        return json.load(f)

def represent_none(self, _):
    return self.represent_scalar('tag:yaml.org,2002:null', '~')

yaml.SafeDumper.add_representer(type(None), represent_none)

def replace_none_with_null(data):
    if isinstance(data, dict):
        return {k: replace_none_with_null(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [replace_none_with_null(item) for item in data]
    elif data == "None":
        return None
    else:
        return data

def main():
    # Load the template
    with open(os.path.join(TEMPLATE_DIR, TEMPLATE_FILE), 'r') as f:
        template_content = f.read()
    
    # Replace custom delimiters with Jinja2 delimiters
    template_content = template_content.replace('<<', '{{').replace('>>', '}}')

    # Create Jinja2 environment and template
    env = Environment(loader=BaseLoader())
    template = env.from_string(template_content)

    # Load JSON data
    json_data = {}
    for file in os.listdir(EXAMPLES_DIR):
        if file.endswith('.json'):
            name = os.path.splitext(file)[0]
            json_data[name] = load_json(os.path.join(EXAMPLES_DIR, file))

    # Render the template
    rendered_yaml = template.render(**json_data)

    # Parse the rendered YAML
    parsed_yaml = yaml.safe_load(rendered_yaml)

    # Replace "None" with None (which will be represented as ~ in YAML)
    cleaned_yaml = replace_none_with_null(parsed_yaml)

    # Write the final YAML to a file
    output_file = os.path.join(TEMPLATE_DIR, 'openapi-overrides.yml')
    with open(output_file, 'w') as f:
        f.write("# WARNING: This file is auto-generated. Do not edit this file directly.\n")
        f.write("# Use the populate_template.py script to update this file.\n\n")
        yaml.dump(cleaned_yaml, f, sort_keys=False, default_flow_style=False, Dumper=yaml.SafeDumper)

    print(f"YAML file generated successfully: {output_file}")

if __name__ == "__main__":
    main()