#!/usr/bin/env bash

# This script is used to sync the OpenAPI specification from the backend

# TO USE:
# 0. install yq and prettier
# brew install yq
# npm install -g prettier
# 1. Set API_URL to the URL of the backend API (if local, make sure it is running)
# 2. Run the script

# API_URL=https://api.humanloop.com
API_URL=http://localhost:80

# Print a beautiful styled message
echo "🔄 Starting the synchronization of the OpenAPI specification..."

# This script will download the latest OpenAPI specification from backend.
PROJECT_ROOT="$(pwd)/$(dirname "$0")/../"

# Convert to yaml 
response=$(curl -s $API_URL/v4/openapi.json)
if [ -z "$response" ]; then
  echo "❌ Error: No response from the API at $API_URL/v4/openapi.json"
  echo "❌ Will not regenerate v4 OpenAPI spec"
  exit 1
fi

# Add warning to the top of the file, not to edit it directly
echo "#
# WARNING: This file is auto-generated. Do not edit this file directly.
# Use the sync_openapi.sh script to update this file.
#" > $PROJECT_ROOT/fern/apis/v4/openapi/openapi.yml
echo "$response" | yq eval -P - >> $PROJECT_ROOT/fern/apis/v4/openapi/openapi.yml

# Run prettier on the file
prettier --write $PROJECT_ROOT/fern/apis/v4/openapi/openapi.yml

# Print a beautiful styled message
echo "...✨ formatted successfully!"
echo "✅ Successfully synchronized v4 OpenAPI specification and formatted it with prettier."

echo 
# ----------------------------

# Convert to yaml 
response=$(curl -s $API_URL/v5/openapi.json)
if [ -z "$response" ]; then
  echo "❌ Error: No response from the API at $API_URL/v5/openapi.json"
  echo "❌ Will not regenerate v5 OpenAPI spec"
  exit 1
fi
echo "#
# WARNING: This file is auto-generated. Do not edit this file directly.
# Use the sync_openapi.sh script to update this file.
#" > $PROJECT_ROOT/fern/apis/v5/openapi/openapi.yml
echo "$response" | yq eval -P - >> $PROJECT_ROOT/fern/apis/v5/openapi/openapi.yml

# Run prettier on the file
prettier --write $PROJECT_ROOT/fern/apis/v5/openapi/openapi.yml

# Print a beautiful styled message
echo "...✨ formatted successfully!"
echo "✅ Successfully synchronized v5 OpenAPI specification and formatted it with prettier."

# Run the populate script to fill in the overrides
python $PROJECT_ROOT/scripts/populate_template.py

# Print a beautiful styled message
echo "✨ YAML file generated successfully: $PROJECT_ROOT/fern/apis/v5/openapi/openapi-overrides.yml"
echo "✅ Successfully populated the template with overrides."