name: Release Python SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the SDK you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install the Fern CLI
        run: npm install -g fern-api

      - name: Generate Python SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        #   PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          fern generate --group python-sdk --version ${{ inputs.version }} --log-level debug

      - name: Update Code Snippets
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --docs
